source "http://rubygems.org"

gem "rails", "2.3.18"
gem "mysql2", "~> 0.2.18"
gem "rubyzip", "~> 0.9.4"
gem "oauth", "~> 0.4.3"
gem "libxml-ruby", '~> 2.7.0', :require=>"libxml"
gem "rmagick", "2.13.1", :require => 'RMagick'
gem "dsl_accessor", "~> 0.4.0"
gem "ruby-openid", "~> 2.1.8"
gem "openurl", "~> 0.2.0"
gem "curb", "~> 0.7.8"
gem "marc", "~> 0.4.3"
gem "ruby-hmac", "~> 0.4.0"
gem "passenger", "~> 3.0.19"
gem "htmlentities", "~> 4.3.1"
gem "taverna-scufl", "~> 0.7.2"
gem "taverna-t2flow", "~> 0.5.0"
gem "rdf", "~> 1.0.6"
gem "rdf-raptor", "~> 1.0.1"
gem "rdf-n3", "~> 1.0.0"
gem "rdf-turtle", "~> 1.0.6"
gem "recaptcha", "~> 0.3.4"
gem "encrypted_strings", "~> 0.3.3"
gem "encrypted_attributes", "~> 0.4.1"
gem "sunspot_rails", "~> 2.0.0"
gem "sunspot_solr", "~> 2.0.0"
gem "will_paginate", "~> 2.3.16"
gem "open_id_authentication", "~> 1.1.0"
gem "simple-rss", "~> 1.2.3"
gem "net-http-persistent", "~> 2.8"
gem "delayed_job", "~>2.0.4"
gem "wf4ever-transformation-client", "~> 0.3.0"
gem "sanitize", "~> 2.0.6"
gem 'datacite_doi_ify'

