default: &default
  adapter: mysql2

production:
  <<: *default
  host: <%= ENV["MYSQL_HOST"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
