# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "blobs", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "local_name",       :string
    t.column "content_type",     :string
    t.column "data",             :binary
  end

  create_table "bookmarks", :force => true do |t|
    t.column "title",             :string,   :limit => 50, :default => ""
    t.column "created_at",        :datetime,                               :null => false
    t.column "bookmarkable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "bookmarkable_id",   :integer,                :default => 0,  :null => false
    t.column "user_id",           :integer,                :default => 0,  :null => false
  end

  add_index "bookmarks", ["user_id"], :name => "fk_bookmarks_user"

  create_table "comments", :force => true do |t|
    t.column "title",            :string,   :limit => 50, :default => ""
    t.column "comment",          :text
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "fk_comments_user"

  create_table "contributions", :force => true do |t|
    t.column "contributor_id",     :integer
    t.column "contributor_type",   :string
    t.column "contributable_id",   :integer
    t.column "contributable_type", :string
    t.column "policy_id",          :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
  end

  create_table "friendships", :force => true do |t|
    t.column "user_id",     :integer
    t.column "friend_id",   :integer
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
  end

  create_table "memberships", :force => true do |t|
    t.column "user_id",     :integer
    t.column "network_id",  :integer
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
  end

  create_table "messages", :force => true do |t|
    t.column "from",       :integer
    t.column "to",         :integer
    t.column "subject",    :string
    t.column "body",       :text
    t.column "reply_id",   :integer
    t.column "created_at", :datetime
    t.column "read_at",    :datetime
  end

  create_table "networks", :force => true do |t|
    t.column "user_id",    :integer
    t.column "title",      :string
    t.column "unique",     :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "permissions", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "policy_id",        :integer
    t.column "download",         :boolean,  :default => false
    t.column "edit",             :boolean,  :default => false
    t.column "view",             :boolean,  :default => false
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "pictures", :force => true do |t|
    t.column "user_id", :integer
    t.column "data",    :binary
  end

  create_table "policies", :force => true do |t|
    t.column "contributor_id",     :integer
    t.column "contributor_type",   :string
    t.column "name",               :string
    t.column "download_public",    :boolean,  :default => true
    t.column "edit_public",        :boolean,  :default => true
    t.column "view_public",        :boolean,  :default => true
    t.column "download_protected", :boolean,  :default => true
    t.column "edit_protected",     :boolean,  :default => true
    t.column "view_protected",     :boolean,  :default => true
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
  end

  create_table "profiles", :force => true do |t|
    t.column "user_id",     :integer
    t.column "picture_id",  :integer
    t.column "email",       :string
    t.column "website",     :string
    t.column "description", :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ratings", :force => true do |t|
    t.column "rating",        :integer,                :default => 0
    t.column "created_at",    :datetime,                               :null => false
    t.column "rateable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "rateable_id",   :integer,                :default => 0,  :null => false
    t.column "user_id",       :integer,                :default => 0,  :null => false
  end

  add_index "ratings", ["user_id"], :name => "fk_ratings_user"

  create_table "relationships", :force => true do |t|
    t.column "network_id",  :integer
    t.column "relation_id", :integer
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
    t.column "user_id",       :integer
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "openid_url", :string
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "workflow_versions", :force => true do |t|
    t.column "workflow_id",      :integer
    t.column "version",          :integer
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "scufl",            :binary
    t.column "image",            :string
    t.column "title",            :string
    t.column "unique",           :string
    t.column "description",      :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "workflows", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "scufl",            :binary
    t.column "image",            :string
    t.column "title",            :string
    t.column "unique",           :string
    t.column "description",      :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "version",          :integer
  end

end
